# Generated by Django 4.2.9 on 2026-02-27 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True)),
                ('entry_point', models.CharField(help_text='Frontend route or external URL', max_length=500)),
                ('example_input', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['name'],
            },
        ),
    ]
